name: l10n
version: 1.3.2

author: Mike Mitterer  <office@mikemitterer.at>
description: Creates translatable PO-Files, strong orientation to xgettext
homepage: https://github.com/MikeMitterer/dart-l10n-gettext

environment:
  sdk: '>=1.12.0 <2.0.0'

# Add the bin/mkl10n.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  mkl10n:

dependencies:
  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=0.5.0 <1.0.0'
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  intl: ^0.15.0

  validate: ^1.0.0

  args: ^1.4.0

  dryice: ^1.8.0
    # path: /Volumes/Daten/DevLocal/DevDart/dice

  which: "^0.1.3"

  yaml: ^2.1.0

  optional: ^2.0.0

dev_dependencies:
  test: any

  build_runner: ^0.8.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0

