name: web
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Mike Mitterer <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  l10n: # ^1.0.0
    path: ../..

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
